const {chromium}=require('/Users/tiagopace/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:'/Users/tiagopace/Library/Caches/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-mac-arm64/chrome-headless-shell'});let online=false;const posts=[],errors=[],audits=[];const origin='http://127.0.0.1:4182';
async function page(){const p=await browser.newPage({viewport:{width:360,height:800},isMobile:true,hasTouch:true});p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(u.origin!==origin)return r.abort();if(u.pathname.startsWith('/api/')){if(q.method()==='POST')posts.push(q.postDataJSON());return r.fulfill({status:online?200:503,contentType:'application/json',body:JSON.stringify(online?{ok:true,ranking:[]}:{ok:false,retryable:true})})}return r.continue()});return p}
async function capture(p,name){await p.screenshot({path:`/tmp/pitstop-story/${name}-360.png`});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.addScriptTag({path:'/tmp/pitstop-frontend-review/tooling/node_modules/axe-core/axe.min.js'});const a=await p.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));assert.equal(a.violations.length,0,JSON.stringify(a.violations.map(x=>x.id)));audits.push(name)}
const p=await page();await p.goto(origin);await capture(p,'home');for(const game of ['Corrida','Blocos','Sudoku','Cruzadas']){await p.getByRole('button',{name:`Jogar ${game}`,exact:true}).click();assert.equal(await p.locator('canvas').count(),0);await capture(p,`intro-${game.toLowerCase()}`);await p.getByRole('button',{name:'Fechar',exact:true}).click()}
await p.getByRole('button',{name:'Jogar Corrida',exact:true}).click();await p.getByRole('button',{name:'Cadastrar e jogar',exact:true}).click();await p.getByRole('button',{name:'Continuar',exact:true}).click();assert.equal(await p.evaluate(()=>document.activeElement.id),'nome');await p.locator('#nome').fill('Pessoa Teste');await p.locator('#telefone').fill('95991381037');assert.equal(await p.locator('#telefone').inputValue(),'(95) 9 9138-1037');await p.locator('#aceite').check();await capture(p,'cadastro-antes');await p.getByRole('button',{name:'Continuar',exact:true}).click();await capture(p,'perfil');assert.equal(await p.locator('canvas').count(),0);await p.getByRole('button',{name:'Sim, rodo por aplicativo',exact:true}).click();await p.getByRole('button',{name:'Renda complementar',exact:true}).click();await p.locator('canvas').waitFor();await capture(p,'corrida');await p.getByRole('heading',{name:'Fim da partida',exact:true}).waitFor({timeout:60000});await capture(p,'convite-final');assert(posts.some(x=>x.app===true&&x.atividade==='Renda complementar'));assert(posts.some(x=>x.partidaId&&Number.isInteger(x.duracao)));await p.getByRole('button',{name:'Quero uma proposta personalizada',exact:true}).click();await capture(p,'proposta');assert((await p.getByRole('link',{name:'Pedir cotação pelo WhatsApp'}).getAttribute('href')).includes('wa.me'));online=true;await p.evaluate(()=>window.dispatchEvent(new Event('online')));await p.waitForFunction(()=>JSON.parse(localStorage.getItem('pitstop-hemissul.lead-queue')).length===0);await p.getByRole('button',{name:'Outros jogos',exact:true}).click();
for(const game of ['Blocos','Sudoku','Cruzadas']){await p.getByRole('button',{name:`Jogar ${game}`,exact:true}).click();await p.getByRole('button',{name:`Começar ${game}`,exact:true}).click();if(game==='Sudoku')await p.getByRole('button',{name:/^Fácil/}).click();await p.waitForTimeout(400);await capture(p,game.toLowerCase());await p.getByRole('button',{name:'← Outros jogos',exact:true}).click()}
assert(await p.evaluate(()=>!JSON.stringify(window.dataLayer).includes('Pessoa Teste')));
const guest=await page();await guest.goto(origin);await guest.getByRole('button',{name:'Jogar Corrida',exact:true}).click();await guest.getByRole('button',{name:'Jogar sem cadastrar',exact:true}).click();await guest.getByRole('heading',{name:'Fim da partida',exact:true}).waitFor({timeout:60000});await guest.getByRole('button',{name:'Quero uma proposta personalizada',exact:true}).click();await guest.locator('#nome').fill('Visitante Teste');await guest.locator('#telefone').fill('9536231234');assert.equal(await guest.locator('#telefone').inputValue(),'(95) 3623-1234');await guest.locator('#aceite').check();await guest.getByRole('button',{name:'Continuar',exact:true}).click();await guest.getByRole('button',{name:'Não',exact:true}).click();await guest.getByRole('heading',{name:'Cotação em um toque',exact:true}).waitFor();await capture(guest,'visitante-proposta');assert.equal(errors.length,0,errors.join('\n'));const result={passed:true,viewport:'360x800',screens:audits.length,axeViolations:0,flows:['cadastro antes da partida','perfil de aplicativo','fila e reconexão','convite final','cadastro opcional após jogar','retorno sem repetir cadastro'],network:'API simulada e requisições externas bloqueadas'};fs.writeFileSync('/tmp/pitstop-story/results.json',JSON.stringify(result,null,2));console.log(result);await browser.close()})().catch(e=>{console.error(e);process.exit(1)})
