const {chromium}=require('/Users/tiagopace/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const origin='http://127.0.0.1:4182';
(async()=>{
const browser=await chromium.launch({executablePath:'/Users/tiagopace/Library/Caches/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-mac-arm64/chrome-headless-shell'});
const results=await Promise.all(['offline','refused','storage','sent'].map(async mode=>{
 const page=await browser.newPage({viewport:{width:360,height:800},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
 const errors=[],posts=[]; let online=mode==='sent';page.on('pageerror',e=>errors.push(e.message));
 if(mode==='storage')await page.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('blocked','QuotaExceededError')}});
 await page.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.origin!==origin)return route.abort();if(u.pathname.startsWith('/api/')){if(req.method()==='GET')return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,retryable:true})});posts.push({url:u.pathname,...req.postDataJSON()});await new Promise(r=>setTimeout(r,100));return route.fulfill({status:online?200:mode==='refused'?400:503,contentType:'application/json',body:JSON.stringify(online?{ok:true}:{ok:false,retryable:mode!=='refused',error:mode==='refused'?'invalido':'indisponivel',campo:'telefone'})})}return route.continue()});
 await page.goto(origin+'/?posto=01');await page.getByRole('button',{name:'Jogar Corrida',exact:true}).click();await page.locator('canvas').waitFor();const started=Date.now();
 if(mode==='offline'){await page.getByRole('button',{name:'Pausar',exact:true}).click();const score=await page.locator('.score').innerText();await page.waitForTimeout(4000);assert.equal(await page.locator('.score').innerText(),score);await page.screenshot({path:`/tmp/pitstop-ui-status/pause-360.png`});await page.getByRole('button',{name:'Continuar',exact:true}).click()}
 await page.getByRole('heading',{name:'Salve seu recorde'}).waitFor({timeout:60000});const wall=(Date.now()-started)/1000;
 await page.getByRole('button',{name:'Salvar recorde',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'nome');await page.locator('#nome').fill('Pessoa Teste');await page.getByRole('button',{name:'Salvar recorde',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'telefone');
 await page.locator('#telefone').pressSequentially('95991381037');assert.equal(await page.locator('#telefone').inputValue(),'(95) 9 9138-1037');await page.screenshot({path:`/tmp/pitstop-ui-status/${mode}-mobile-mask-360.png`});await page.locator('#telefone').fill('');await page.locator('#telefone').pressSequentially('9536231234');assert.equal(await page.locator('#telefone').inputValue(),'(95) 3623-1234');await page.getByRole('button',{name:'Salvar recorde',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'aceite');await page.screenshot({path:`/tmp/pitstop-ui-status/${mode}-landline-error-360.png`});await page.locator('#aceite').check();await page.getByRole('button',{name:'Salvar recorde',exact:true}).click();await page.getByRole('heading',{name:'Você roda por aplicativo?'}).waitFor();await page.waitForTimeout(800);
 await page.getByRole('button',{name:'Não',exact:true}).click();await page.waitForTimeout(800);
 const note=page.locator('dialog .delivery-status');
 if(mode==='refused'){await page.getByText('Cadastro não aceito pelo servidor.',{exact:false}).waitFor();assert(!(await note.innerText()).includes('Cadastro enviado.'))}
 if(mode==='storage')await page.getByText('Não foi possível guardar seus dados neste aparelho.',{exact:false}).waitFor();
 if(mode==='offline')await page.getByText('Cadastro na fila de envio.',{exact:true}).waitFor();
 if(mode==='sent')await page.getByText('Cadastro enviado.',{exact:true}).waitFor();
 await page.screenshot({path:`/tmp/pitstop-ui-status/${mode}-360.png`});
 const scorePost=posts.find(p=>p.url==='/api/ranking');assert(scorePost);assert(Number.isInteger(scorePost.duracao)&&scorePost.duracao>0);if(mode==='offline')assert(scorePost.duracao<=Math.ceil(wall)-3,JSON.stringify({duration:scorePost.duracao,wall}));
 await page.addScriptTag({path:'/tmp/pitstop-frontend-review/tooling/node_modules/axe-core/axe.min.js'});const audit=await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));assert.equal(audit.violations.length,0,JSON.stringify(audit.violations.map(v=>v.id)));
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.evaluate(()=>!JSON.stringify(window.dataLayer).includes('Pessoa Teste')));
 if(mode==='offline'){online=true;await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.waitForFunction(()=>JSON.parse(localStorage.getItem('pitstop-hemissul.lead-queue')).length===0&&JSON.parse(localStorage.getItem('pitstop-hemissul.score-queue')).length===0);await page.waitForTimeout(1200);assert(!(await note.innerText()).includes('na fila de envio'));await page.screenshot({path:'/tmp/pitstop-ui-status/reconnected-360.png'});await page.getByRole('button',{name:'Outros jogos',exact:true}).click();await page.screenshot({path:'/tmp/pitstop-ui-status/home-360.png'});await page.getByRole('button',{name:'Jogar Corrida',exact:true}).click();await page.getByRole('heading',{name:'Fim da partida',exact:true}).waitFor({timeout:45000});await page.waitForTimeout(400);const rounds=posts.filter(p=>p.url==='/api/ranking');assert(new Set(rounds.map(p=>p.partidaId)).size===2);assert(rounds.every(p=>Number.isInteger(p.duracao)));await page.screenshot({path:'/tmp/pitstop-ui-status/returning-player-360.png'});}
 assert.equal(errors.length,0,errors.join('\n'));await page.close();return {mode,passed:true,duration:scorePost.duracao,wall,posts:posts.length,axe:0};
}));await browser.close();fs.writeFileSync('/tmp/pitstop-ui-status/results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results))
})().catch(e=>{console.error(e);process.exit(1)})
